# Use the new trusty image
dist: trusty
sudo: false

# Node LTS version
language: node_js
node_js: '7'

# Cache yarn
cache: yarn

addons:
  apt:
    packages:
    # Install Wine, so we can build win32 packages
    - wine

# Run package.json scripts
script:
- yarnpkg dist
