# Use osx
os: osx

# Install needed software
before_install:
  - brew install yarn imagemagick mono rpm dpkg fakeroot
  - brew cask install wine-stable

# Run package.json scripts
script:
- yarn install
- yarn run icons
- yarn run make
- yarn run publish
