# Use osx
os: osx

# Install needed software
before_install:
  - brew install yarn imagemagick mono
  - brew cask install wine-stable

# Run package.json scripts
script:
- yarn install
- yarn dist -wml --publish onTagOrDraft
