# Use osx
os: osx
osx_image: xcode12.5

# Install needed software
before_install:
  - brew install yarn imagemagick

# Run package.json scripts
script:
- yarn install
- yarn dist -wml --publish onTagOrDraft
