steps:
  - name: qemu
    privileged: true
    image: multiarch/qemu-user-static
    commands:
      - /register --reset -p yes

  - name: build kanbanflow
    image: electronuserland/builder:wine
    commands:
      - yarn install
      - yarn dist -wl --publish onTagOrDraft
